### ISSUE TITLE
"Refund"

### ISSUE THREAD

**Issue by herrborecki** [aclich/Holocure_save_editor#3]
After selecting the save file and pressing confirm, an error appears with the words "Refund"
![error](https://user-images.githubusercontent.com/65131515/177009468-136d17ba-0d15-45bb-b7c1-e9d22b8ee3da.png)

**Comment by herrborecki** [comment]
nvm im just stupid xD

**Comment by Rezina287** [comment]
i have the same problem, idk what did i do wrong
