### ISSUE TITLE
Please make a scrollbar for 0.0.3 Pilot

### ISSUE THREAD

**Issue by TuanAnh2901** [aclich/Holocure_save_editor#6]
I try to use the demo version and can't save file because the height is too large to do anything without a scrollbar
![image](https://user-images.githubusercontent.com/102243051/190679398-4020187c-4c60-4b16-b756-9086e8461418.png)

**Comment by rnveach** [comment]
Just my opinion, but maybe consider tabs if possible.

**Comment by aclich** [comment]
@TuanAnh2901 
@rnveach 
Thanks for the suggestion and report the problem!
I'll release a version with scroll bar ASAP.

**Comment by aclich** [comment]
@TuanAnh2901 
Sorry for awaited. I've already released a new version with scrollbar in editor page. Hope it could solve the problem well.
https://github.com/aclich/Holocure_save_editor/releases/download/v0.0.3-beta/HoloCure_Save_Tool_v0.0.3_Beta.zip
