### ISSUE TITLE
unhashable type "list"

### ISSUE THREAD

**Issue by TuanAnh2901** [aclich/Holocure_save_editor#8]
I don't know why I have this error today, but it make me can't edit save file :v ( Have tried with new save file )
![image](https://user-images.githubusercontent.com/102243051/190886705-89ed9d56-d61f-495a-9f75-43d82679347f.png)

**Comment by aclich** [comment]
@TuanAnh2901 Can you please send your save file content to me? You can just open the save with text editor and copy and paste the content in a reply. Thank you!

**Comment by TuanAnh2901** [comment]
> @TuanAnh2901 Can you please send your save file content to me? You can just open the save with text editor and copy and paste the content in a reply. Thank you!

I have edited it by online save editor and this is the text:
3b67a5bc4a1018bdd6dd6130bd667c919a435a8d524f94e902d218cf38d88c5c447239824440bf3eeyAiZm9vZCI6IDk5OSwgImdyb3d0aCI6IDEsICJzcGVjVW5sb2NrIjogMSwgIkdST2ZmIjogMCwgImhhc3RlIjogOTk5OSwgImhvbG9Db2lucyI6IDk5OTk5ODM2NiwgInVubG9ja2VkSXRlbXMiOiBbICJCb2R5UGlsbG93IiwgIkZ1bGxNZWFsIiwgIlBpa2lQaWtpUGltYW4iLCAiU3VjY3VidXNIb3JuIiwgIkhlYWRwaG9uZXMiLCAiVWJlclNoZWVwIiwgIkhvbHlNaWxrIiwgIlNha2UiLCAiRmFjZU1hc2siLCAiQ3JlZGl0Q2FyZCIsICJTdHVkeUdsYXNzZXMiLCAiR29yaWxsYXNQYXciLCAiSW5qZWN0aW9uQXNhY29jbyIsICJJZG9sQ29zdHVtZSIsICJTdXBlckNoYXR0b1RpbWUiLCAiRW5lcmd5RHJpbmsiLCAiUGx1c2hpZSIsICJIYWx1IiwgIkJhbmRhaWQiLCAiUGlnZ3lCYW5rIiwgIk1lbWJlcnNoaXAiLCAiQ2hpY2tlbnNGZWF0aGVyIiwgIkdXU1BpbGwiLCAiTGltaXRlciIgXSwgInRlYXJzIjogWyBbICJteXRoIiwgOTk5OTk5IF0sIFsgImNvdW5jaWxIb3BlIiwgOTk5OTk5IF0sIFsgImdhbWVycyIsIDk5OTk5OSBdLCBbICJnZW4wIiwgOTk5OTk5IF0sIFsgImdlbjEiLCAwIF0gXSwgImNvbXBsZXRlZFN0YWdlcyI6IFsgWyAiU1RBR0UgMSIsIFsgImJhZSIgXSBdLCBbICJTVEFHRSAyIiwgW10gXSwgWyAiU1RBR0UgMSAoSEFSRCkiLCBbXSBdIF0sICJBVEsiOiA5OTk5OTksICJ1bmxvY2tlZFN0YWdlcyI6IFsgIlNUQUdFIDEiLCAiU1RBR0UgMiIsICJTVEFHRSAxIChIQVJEKSIgXSwgInVubG9ja2VkV2VhcG9ucyI6IFsgIlBzeWNob0F4ZSIsICJHbG93c3RpY2siLCAiU3BpZGVyQ29va2luZyIsICJUYWlscGx1ZyIsICJCTEJvb2siLCAiRWxpdGVMYXZhIiwgIkhvbG9Cb21iIiwgIkhvbG9MYXNlciIsICJDdXR0aW5nQm9hcmQiLCAiSWRvbFNvbmciLCAiV2FteVdhdGVyIiwgIlhQb3RhdG8iLCAiQ0VPVGVhcnMiIF0sICJyZWdlbiI6IDk5OTk5OSwgInNwZWNDRFIiOiA5OTk5OTksICJlbmhhbmNlVXAiOiA5OTk5OTksICJFWFAiOiA5OTk5OTksICJtb25leUdhaW4iOiA5OTk5OTksICJyZXJvbGwiOiA5OTk5OTk5OTksICJzZWVuQ29sbGFicyI6IFsgIkJMTG92ZXIiLCAiRWxpdGVDb29raW5nIiwgIkRyYWdvbkJlYW0iLCAiTWlDb21ldCIsICJMaWdodEJlYW0iLCAiQnJlYXRoZUluQXNhY29jbyIsICJGbGF0Qm9hcmQiLCAiSWRvbENvbmNlcnQiLCAiTWFyaUxhbXkiLCAiUmFwRG9nIiwgIkJyb2tlbkRyZWFtcyIsICJTdHJlYW1PZlRlYXJzIiBdLCAicmVmdW5kIjogMCwgImNoYWxsZW5nZSI6IDAsICJ1bmxvY2tlZENoYXJhY3RlcnMiOiAwLCAidW5sb2NrZWRPdXRmaXRzIjogWyAiZGVmYXVsdCIsICJrdXJva2FtaSIsICJmYXVuYUFsdDEiLCAiYW1lQWx0MSIsICJpbmFBbHQxIiwgImd1cmFBbHQxIiwgImNhbGxpQWx0MSIsICJraWFyYUFsdDEiLCAiaXJ5c0FsdDEiLCAiYmFlQWx0MSIsICJzYW5hQWx0MSIsICJtdW1laUFsdDEiLCAia3JvbmlpQWx0MSIgXSwgImVsaW1pbmF0ZSI6IDk5OTk5OSwgInJhbmRvbU1vbmV5S2V5IjogOTk5OTk5LCAicGlja3VwUmFuZ2UiOiA5OTk5OTksICJTUEQiOiA5OTksICJEUiI6IDk5OTk5OSwgImNoYXJhY3RlcnMiOiBbIFsgImtyb25paSIsIDk5OTk5OSBdLCBbICJmdWJ1a2kiLCA5OTk5OTkgXSwgWyAiY2FsbGkiLCA5OTk5OTkgXSwgWyAic3Vpc2VpIiwgOTk5IF0sIFsgInJhbmRvbSIsIDk5OTk5OSBdLCBbICJub25lIiwgMCBdLCBbICJyb2JvY28iLCA5OTk5OTkgXSwgWyAiZmF1bmEiLCA5OTk5OTkgXSwgWyAic29yYSIsIDk5OTk5OSBdLCBbICJtaWtvIiwgOTk5OTk5IF0sIFsgImVtcHR5IiwgOTk5OTk5IF0sIFsgImd1cmEiLCA5OTk5OTkgXSwgWyAic2FuYSIsIDk5OTk5OSBdLCBbICJva2F5dSIsIDk5OSBdLCBbICJpcnlzIiwgOTk5IF0sIFsgImJhZSIsIDk5OSBdLCBbICJhemtpIiwgOTk5IF0sIFsgImtpYXJhIiwgOTk5IF0sIFsgImluYSIsIDk5OSBdLCBbICJrb3JvbmUiLCA5OTkgXSwgWyAibWlvIiwgOTk5IF0sIFsgImFtZSIsIDk5OSBdLCBbICJtdW1laSIsIDk5OSBdIF0sICJIUCI6IDk5OTk5OTk5OSwgImNyaXQiOiA5OTk5OTl9

**Comment by aclich** [comment]
@TuanAnh2901  Thank you for providing your save file.
In the latest game build there's a new key in the save with new format and can not be recognized by this tool.
A new version will be released later in today to solve this problem.
Again, thanks for reporting the issue !

**Comment by aclich** [comment]
New release
>https://github.com/aclich/Holocure_save_editor/releases/download/v0.0.3-C/HoloCure_Save_Tool_v0.0.3_C.zip
